### ISSUE TITLE
[Usage] Batch inference with Llava 1.5

### ISSUE THREAD

**Issue by kimihailv** [haotian-liu/LLaVA#709]
### Describe the issue

Currenty, only inference with batch_size=1 is possible. If I undestood correctly, these things should be changed to make batch inference:

1. position_ids should be shifted, because of left padding
2. Attention mask should be passed and transformed for multimodal forward

Maybe someone has managed to adapt the code?

**Comment by rabiulcste** [comment]
Here's a processor that I wrote to make it work.
```
from LLaVA.llava.constants import DEFAULT_IM_END_TOKEN, DEFAULT_IM_START_TOKEN, DEFAULT_IMAGE_TOKEN, IMAGE_TOKEN_INDEX
from LLaVA.llava.conversation import conv_templates
from LLaVA.llava.mm_utils import tokenizer_image_token


class LlaVaProcessor:
    def __init__(self, tokenizer, image_processor, mm_use_im_start_end):
        self.mm_use_im_start_end = mm_use_im_start_end
        self.tokenizer = tokenizer
        self.image_processor = image_processor
        self.conv_mode = "llava_v1"

    def load_demo_images(image_files: Union[List[str], str]):
        if type(image_files) is list:
            out = []
            for image_file in image_files:
                image = Image.open(image_file).convert("RGB")
                out.append(image)
        else:
            out = Image.open(image_files).convert("RGB")
        return out

    # TODO: refactor this, not working
    def get_processed_tokens_demo(self, text: str, image_files: Union[List[str], str]):
        if self.mm_use_im_start_end:
            qs = (
                qs
                + "\n"
                + DEFAULT_IM_START_TOKEN
                + DEFAULT_IMAGE_PATCH_TOKEN * image_token_len
                + DEFAULT_IM_END_TOKEN
                + "\n"
                + DEFAULT_IM_START_TOKEN
                + DEFAULT_IMAGE_PATCH_TOKEN * image_token_len
                + DEFAULT_IM_END_TOKEN
            )
        else:
            qs = (
                qs
                + "\n"
                + DEFAULT_IMAGE_PATCH_TOKEN * image_token_len
                + "\n"
                + DEFAULT_IMAGE_PATCH_TOKEN * image_token_len
            )

        conv = conv_templates[self.conv_mode].copy()
        conv.append_message(conv.roles[0], text)
        conv.append_message(conv.roles[1], None)
        prompt = conv.get_prompt()

        images = self.load_demo_images(image_files)
        image_tensor = torch.stack(
            [self.image_processor.preprocess(image, return_tensors="pt")["pixel_values"][0] for image in images]
        )

        input_ids = (
            tokenizer_image_token(text, self.tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pt").unsqueeze(0).cuda()
        )

        return image_tensor, input_ids

    def format_text(self, text: str):
        if self.mm_use_im_start_end:
            text = DEFAULT_IM_START_TOKEN + DEFAULT_IMAGE_TOKEN + DEFAULT_IM_END_TOKEN + "\n" + text
        else:
            text = DEFAULT_IMAGE_TOKEN + "\n" + text

        conv = conv_templates[self.conv_mode].copy()
        conv.append_message(conv.roles[0], text)
        conv.append_message(conv.roles[1], None)
        text = conv.get_prompt()

        return text

    def load_image(self, image_path: str):
        return Image.open(image_path).convert("RGB")

    @staticmethod
    def pad_sequence_to_max_length(sequence, max_length, padding_value=0):
        """Pad a sequence to the desired max length."""
        if len(sequence) >= max_length:
            return sequence
        return torch.cat([torch.full((max_length - len(sequence),), padding_value, dtype=sequence.dtype), sequence])

    def get_processed_tokens(self, text: str, image_path: str):
        prompt = self.format_text(text)
        image = self.load_image(image_path)

        input_ids = tokenizer_image_token(prompt, self.tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pt").unsqueeze(0)
        image_tensor = self.image_processor.preprocess(image, return_tensors="pt")["pixel_values"][0]

        return image_tensor, input_ids

    def get_processed_tokens_batch(self, batch_text: List[str], image_paths: List[str]):
        prompt = [self.format_text(text) for text in batch_text]
        images = [self.load_image(image_path) for image_path in image_paths]

        batch_input_ids = [
            tokenizer_image_token(prompt, self.tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pt") for prompt in prompt
        ]

        # Determine the maximum length of input_ids in the batch
        max_len = max([len(seq) for seq in batch_input_ids])
        # Pad each sequence in input_ids to the max_len
        padded_input_ids = [self.pad_sequence_to_max_length(seq.squeeze(), max_len) for seq in batch_input_ids]
        batch_input_ids = torch.stack(padded_input_ids)

        batch_image_tensor = self.image_processor(images, return_tensors="pt")["pixel_values"]

        return batch_image_tensor, batch_input_ids
```

You can now do inference
```
                from LLaVA.llava.conversation import (SeparatorStyle,
                                                      conv_templates)
                from LLaVA.llava.mm_utils import KeywordsStoppingCriteria

                conv = conv_templates[processor.conv_mode].copy()
                stop_str = conv.sep if conv.sep_style != SeparatorStyle.TWO else conv.sep2
                keywords = [stop_str]
                stopping_criteria = (
                    [KeywordsStoppingCriteria(keywords, processor.tokenizer, input_ids)]
                    if conv.version == "v0"
                    else None
                )
                input_ids = batch["input_ids"]
                image_tensor = batch["image_tensors"]
                input_ids = input_ids.cuda()

                output_ids = model.generate(
                    input_ids,
                    images=image_tensor.half().cuda(),
                    num_beams=self.args.num_beams,
                    max_new_tokens=self.args.max_length,
                    length_penalty=self.args.length_penalty,
                    use_cache=True,
                    stopping_criteria=stopping_criteria,
                    do_sample=self.args.do_sample,
                    temperature=self.args.temperature,
                    num_return_sequences=self.args.num_return_sequences,
                )
                generated_outputs = processor.tokenizer.batch_decode(
                    output_ids[:, input_ids.shape[1] :], skip_special_tokens=True
                )
                generated_outputs = [out.strip() for out in generated_outputs]
                generated_outputs = [
                    out[: -len(stop_str)] if out.endswith(stop_str) else out for out in generated_outputs
                ]
```

You can also check my [vqa-prompting codebase](https://github.com/rabiulcste/vqazero/tree/main/vqa_zero) for full support!

**Comment by NielsRogge** [comment]
Hi,

Batched inference with LLaVa is supported in Hugging Face Transformers. See here for an example: https://github.com/huggingface/transformers/blob/a49f4acab3c1eea82907e12f82eafbd4673deb39/tests/models/llava/test_modeling_llava.py#L245.

**Comment by david-vectorflow** [comment]
In case anyone else finds this, here is a sample of working batch inference code based on the link above

```python
        prompt_temp = "<|im_start|>system\nAnswer the questions.<|im_end|><|im_start|>user\n<image>\n{}<|im_end|><|im_start|>assistant\n"
        
        prompts=[]
        images = []

        for user_question, base64_image in zip(user_questions, images_data):
            prompt = prompt_temp.format(user_question)
            prompts.append(prompt)

            image_data = base64.b64decode(base64_image)
            image = Image.open(BytesIO(image_data))
            images.append(image)


        # Perform batch inference
        inputs = self.processor(prompts, images=images, return_tensors="pt", padding=True).to("cuda:0")
        output = self.model.generate(**inputs, max_new_tokens=4000)
        
        answer = self.processor.batch_decode(output, skip_special_tokens=True)
```

**Comment by g8a9** [comment]
> Hi,
> 
> Batched inference with LLaVa is supported in Hugging Face Transformers. See here for an example: https://github.com/huggingface/transformers/blob/a49f4acab3c1eea82907e12f82eafbd4673deb39/tests/models/llava/test_modeling_llava.py#L245.

Hey, @NielsRogge I've stumbled upon this issue today. It seems that the same code does not work for `LlavaNextForConditionalGeneration`. Is batched inference for LlavaNext models supported in some other ways?

**Comment by NielsRogge** [comment]
Yes tI'm aware of that, this is being addressed in https://github.com/huggingface/transformers/pull/29850

It will be part of the next Transformers release!

**Comment by hxhcreate** [comment]
```
  if "llava" in self.model_name.lower() and 'hf' in self.model_name.lower():
            questions = [question.replace("<image>", "") for question in questions]  
            images = None
            if image_paths: 
                images = self.load_images(image_paths)
                conversations = [[
                    { 
                        "role": "user","content": 
                        [
                            {"type": "image"},
                            {"type": "text", "text": question},
                           
                        ],
                    },
                ] for question in questions]
            prompts = [self.processor.apply_chat_template(conv, add_generation_prompt=True) for conv in conversations]
            inputs = self.processor(text=prompts, images=images, padding=True, truncation=True, max_length=self.args.max_length, return_tensors='pt').to(self.device, torch.float16)
            with torch.no_grad():
                generated_ids = self.model.generate(**inputs, **self.generation_config)
                generated_ids_trimmed = [
                    out_ids[len(in_ids) :] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
                ]
                outputs = self.processor.batch_decode(generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False)
            outputs = [output.strip() for output in outputs]
```

When I run the above batch_inference_code, I got the following error and I cannot understand

> RuntimeError:The size of tensor a (2955)must match the size of tensor b (28)at non-singleton dimension 0

**Comment by NielsRogge** [comment]
Update here, we now added batch inference in the docs:

* llava: will add docs for it in https://github.com/huggingface/transformers/pull/33393
* llava-next: [docs](https://huggingface.co/docs/transformers/main/en/model_doc/llava_next#multi-image-inference)
* llava-onevision: [docs](https://huggingface.co/docs/transformers/main/en/model_doc/llava_onevision#multi-image-inference)
* qwen2-vl: [docs](https://huggingface.co/docs/transformers/main/en/model_doc/qwen2_vl#batch-mixed-media-inference)

**Comment by hxhcreate** [comment]
Thanks for your reply. But when I running the  sample code here: https://huggingface.co/docs/transformers/main/en/model_doc/llava_next#multi-image-inference
I still get the following error:

<img width="758" alt="image" src="https://github.com/user-attachments/assets/e89bfcfe-4091-416f-b88e-0b65d29b7f22">


I'm using the latest transformer 4.45.dev

**Comment by NielsRogge** [comment]
Thanks for flagging. Will ping @zucchini-nlp here.

Note: all doc code snippets of Transformers get tested, but some are excluded due to their size. LLaVa-NeXT is such an example. We could look into how we can also ensure code snippets of larger models are automatically tested

**Comment by zucchini-nlp** [comment]
@hxhcreate @NielsRogge yes, that is a known issue and I merged a fix few days ago. Unfortunately refactoring broken some things, let me know if updating to the latest `main` solves the issue

**Comment by copperwiring** [comment]
Anyone knowhow to do it without hugging face model. This is what I have so far

```
    for prompt in prompts_batch:
        # Set args.query to the specific prompt in the batch
        args.query = prompt

        # Generate the prompt for each input in the batch, with the correct image handling
        qs = get_prompt(args, model)

        # Create a new conversation template for each prompt in the batch
        conv = conv_templates[args.conv_mode].copy()
        conv.append_message(conv.roles[0], qs)
        conv.append_message(conv.roles[1], None)

        # Add the complete prompt for this instance to the batch
        batched_prompts.append(conv.get_prompt())


    # max length for padding
    max_len = max([len(tokenizer.encode(prompt)) for prompt in batched_prompts])

    tokenizer.padding_side = "left"
    tokenizer.model_max_length = max_len
    
    # Tokenize the batch of prompts
    tokenized_prompts = [
        tokenizer_image_token(prompt, tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pt").unsqueeze(0)
        for prompt in batched_prompts
    ]

    input_ids = torch.cat(tokenized_prompts, dim=0).cuda()

    # Process images if provided (batch image loading and processing)
    if img_files_batch:
        # For each batch, parse image files, load them, and process
        image_files_batch = [image_parser(img_files, args.sep) for img_files in img_files_batch]
        images = [load_images(image_files) for image_files in image_files_batch]
        flat_images = [item for sublist in images for item in sublist]
        images_tensor = process_images(flat_images, image_processor, model.config).to(model.device, dtype=torch.float16)
        image_sizes = [img.size for img in flat_images]
    else:
        images_tensor = None
        image_sizes = None

    attention_mask = torch.ones_like(input_ids)

    with torch.inference_mode(), torch.cuda.amp.autocast():
        outputs = model.forward(
            input_ids=input_ids, 
            images=None if images_tensor is None else images_tensor,
            image_sizes=image_sizes,
            attention_mask=attention_mask
            )
    
    logits = outputs.logits[:, -1, :]  # Get the logits for the last token position
    probabilities = F.softmax(logits, dim=-1).squeeze()

```

This is what I have so far but it doesn't add any padding tokens when I print tokenized_prompts

**Comment by KevinXu-01** [comment]
> Here's a processor that I wrote to make it work.
> 
> ```
> from LLaVA.llava.constants import DEFAULT_IM_END_TOKEN, DEFAULT_IM_START_TOKEN, DEFAULT_IMAGE_TOKEN, IMAGE_TOKEN_INDEX
> from LLaVA.llava.conversation import conv_templates
> from LLaVA.llava.mm_utils import tokenizer_image_token
> 
> 
> class LlaVaProcessor:
>     def __init__(self, tokenizer, image_processor, mm_use_im_start_end):
>         self.mm_use_im_start_end = mm_use_im_start_end
>         self.tokenizer = tokenizer
>         self.image_processor = image_processor
>         self.conv_mode = "llava_v1"
> 
>     def load_demo_images(image_files: Union[List[str], str]):
>         if type(image_files) is list:
>             out = []
>             for image_file in image_files:
>                 image = Image.open(image_file).convert("RGB")
>                 out.append(image)
>         else:
>             out = Image.open(image_files).convert("RGB")
>         return out
> 
>     # TODO: refactor this, not working
>     def get_processed_tokens_demo(self, text: str, image_files: Union[List[str], str]):
>         if self.mm_use_im_start_end:
>             qs = (
>                 qs
>                 + "\n"
>                 + DEFAULT_IM_START_TOKEN
>                 + DEFAULT_IMAGE_PATCH_TOKEN * image_token_len
>                 + DEFAULT_IM_END_TOKEN
>                 + "\n"
>                 + DEFAULT_IM_START_TOKEN
>                 + DEFAULT_IMAGE_PATCH_TOKEN * image_token_len
>                 + DEFAULT_IM_END_TOKEN
>             )
>         else:
>             qs = (
>                 qs
>                 + "\n"
>                 + DEFAULT_IMAGE_PATCH_TOKEN * image_token_len
>                 + "\n"
>                 + DEFAULT_IMAGE_PATCH_TOKEN * image_token_len
>             )
> 
>         conv = conv_templates[self.conv_mode].copy()
>         conv.append_message(conv.roles[0], text)
>         conv.append_message(conv.roles[1], None)
>         prompt = conv.get_prompt()
> 
>         images = self.load_demo_images(image_files)
>         image_tensor = torch.stack(
>             [self.image_processor.preprocess(image, return_tensors="pt")["pixel_values"][0] for image in images]
>         )
> 
>         input_ids = (
>             tokenizer_image_token(text, self.tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pt").unsqueeze(0).cuda()
>         )
> 
>         return image_tensor, input_ids
> 
>     def format_text(self, text: str):
>         if self.mm_use_im_start_end:
>             text = DEFAULT_IM_START_TOKEN + DEFAULT_IMAGE_TOKEN + DEFAULT_IM_END_TOKEN + "\n" + text
>         else:
>             text = DEFAULT_IMAGE_TOKEN + "\n" + text
> 
>         conv = conv_templates[self.conv_mode].copy()
>         conv.append_message(conv.roles[0], text)
>         conv.append_message(conv.roles[1], None)
>         text = conv.get_prompt()
> 
>         return text
> 
>     def load_image(self, image_path: str):
>         return Image.open(image_path).convert("RGB")
> 
>     @staticmethod
>     def pad_sequence_to_max_length(sequence, max_length, padding_value=0):
>         """Pad a sequence to the desired max length."""
>         if len(sequence) >= max_length:
>             return sequence
>         return torch.cat([torch.full((max_length - len(sequence),), padding_value, dtype=sequence.dtype), sequence])
> 
>     def get_processed_tokens(self, text: str, image_path: str):
>         prompt = self.format_text(text)
>         image = self.load_image(image_path)
> 
>         input_ids = tokenizer_image_token(prompt, self.tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pt").unsqueeze(0)
>         image_tensor = self.image_processor.preprocess(image, return_tensors="pt")["pixel_values"][0]
> 
>         return image_tensor, input_ids
> 
>     def get_processed_tokens_batch(self, batch_text: List[str], image_paths: List[str]):
>         prompt = [self.format_text(text) for text in batch_text]
>         images = [self.load_image(image_path) for image_path in image_paths]
> 
>         batch_input_ids = [
>             tokenizer_image_token(prompt, self.tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pt") for prompt in prompt
>         ]
> 
>         # Determine the maximum length of input_ids in the batch
>         max_len = max([len(seq) for seq in batch_input_ids])
>         # Pad each sequence in input_ids to the max_len
>         padded_input_ids = [self.pad_sequence_to_max_length(seq.squeeze(), max_len) for seq in batch_input_ids]
>         batch_input_ids = torch.stack(padded_input_ids)
> 
>         batch_image_tensor = self.image_processor(images, return_tensors="pt")["pixel_values"]
> 
>         return batch_image_tensor, batch_input_ids
> ```
> 
> You can now do inference
> 
> ```
>                 from LLaVA.llava.conversation import (SeparatorStyle,
>                                                       conv_templates)
>                 from LLaVA.llava.mm_utils import KeywordsStoppingCriteria
> 
>                 conv = conv_templates[processor.conv_mode].copy()
>                 stop_str = conv.sep if conv.sep_style != SeparatorStyle.TWO else conv.sep2
>                 keywords = [stop_str]
>                 stopping_criteria = (
>                     [KeywordsStoppingCriteria(keywords, processor.tokenizer, input_ids)]
>                     if conv.version == "v0"
>                     else None
>                 )
>                 input_ids = batch["input_ids"]
>                 image_tensor = batch["image_tensors"]
>                 input_ids = input_ids.cuda()
> 
>                 output_ids = model.generate(
>                     input_ids,
>                     images=image_tensor.half().cuda(),
>                     num_beams=self.args.num_beams,
>                     max_new_tokens=self.args.max_length,
>                     length_penalty=self.args.length_penalty,
>                     use_cache=True,
>                     stopping_criteria=stopping_criteria,
>                     do_sample=self.args.do_sample,
>                     temperature=self.args.temperature,
>                     num_return_sequences=self.args.num_return_sequences,
>                 )
>                 generated_outputs = processor.tokenizer.batch_decode(
>                     output_ids[:, input_ids.shape[1] :], skip_special_tokens=True
>                 )
>                 generated_outputs = [out.strip() for out in generated_outputs]
>                 generated_outputs = [
>                     out[: -len(stop_str)] if out.endswith(stop_str) else out for out in generated_outputs
>                 ]
> ```
> 
> You can also check my [vqa-prompting codebase](https://github.com/rabiulcste/vqazero/tree/main/vqa_zero) for full support!

Thank you for your sharing. It solved my problem!!!

**Comment by Jason-Chi-xx** [comment]
Hi,  I have encountered a problem when running the inference code of llava-next. That is the length of input_ids and images are 9, but the model.generate function would only return the  output_ids with length 1:
output_ids = self.model.generate(
            input_ids,
            images=image_tensor,
            image_sizes=self.image_sizes,
            use_cache=True,
            stopping_criteria=stopping_criteria,
            do_sample=False,
            temperature=0,
            max_new_tokens=256,
        )
      Does someone know the solution? thanks

**Comment by zucchini-nlp** [comment]
@Jason-Chi-xx The model will generate tokens up to `max_new_tokens` and `1` is a feasible length in case the model just generates "eos" as the very first token. Please make sure your prompt is formatted correctly to get a quality generation. I recommend to use `apply_chat_template` for formatting your prompt

**Comment by KevinXu-01** [comment]
> Hi, I have encountered a problem when running the inference code of llava-next. That is the length of input_ids and images are 9, but the model.generate function would only return the output_ids with length 1: output_ids = self.model.generate( input_ids, images=image_tensor, image_sizes=self.image_sizes, use_cache=True, stopping_criteria=stopping_criteria, do_sample=False, temperature=0, max_new_tokens=256, ) Does someone know the solution? thanks

@Jason-Chi-xx Please make sure the input_ids are concatenated. Here are the codes for batched inference:
```
def load_model(rank):
    device = "cuda:" + str(rank)
    model_name = get_model_name_from_path(model_path)
    tokenizer, model, image_processor, context_len = load_pretrained_model(
    model_path, None, model_name, False, False, device
    )
    return tokenizer, model, image_processor, context_len

def pad_sequence_to_max_length(sequence, max_length, padding_value=0):
    """Pad a sequence to the desired max length."""
    if len(sequence) >= max_length:
        return sequence
    return torch.cat([torch.full((max_length - len(sequence),), padding_value, dtype=sequence.dtype), sequence])

"""rank is your device id, qs is the textual prompt, frames are batched images. Tokenizer, model, and image_processor can be obtained when you run load_model."""
def batched_inference(rank, qs, frames, tokenizer, model, image_processor):
    disable_torch_init()
    model_name = get_model_name_from_path(model_path)
    image_token_se = DEFAULT_IM_START_TOKEN + DEFAULT_IMAGE_TOKEN + DEFAULT_IM_END_TOKEN
    if IMAGE_PLACEHOLDER in qs:
        if model.config.mm_use_im_start_end:
            qs = re.sub(IMAGE_PLACEHOLDER, image_token_se, qs)
        else:
            qs = re.sub(IMAGE_PLACEHOLDER, DEFAULT_IMAGE_TOKEN, qs)
    else:
        if model.config.mm_use_im_start_end:
            qs = image_token_se + "\n" + qs
        else:
            qs = DEFAULT_IMAGE_TOKEN + "\n" + qs
    # print(qs)
    if "llama-2" in model_name.lower():
        conv_mode = "llava_llama_2"
    elif "mistral" in model_name.lower():
        conv_mode = "mistral_instruct"
    elif "v1.6-34b" in model_name.lower():
        conv_mode = "chatml_direct"
    elif "v1" in model_name.lower():
        conv_mode = "llava_v1"
    elif "mpt" in model_name.lower():
        conv_mode = "mpt"
    else:
        conv_mode = "llava_v0"

    conv = conv_templates[conv_mode].copy()
    conv.append_message(conv.roles[0], qs)
    conv.append_message(conv.roles[1], None)
    prompts = []
    for i in range(len(frames)):
        prompt = conv.get_prompt()
        prompts.append(prompt)
    pil_images = []
    for frame in frames:
        rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        pil_image = Image.fromarray(rgb_frame)
        pil_images.append(pil_image)
    image_sizes = [x.size for x in pil_images]
    
    images_tensor = process_images(
        pil_images,
        image_processor,
        model.config
    ).to("cuda:"+str(rank), dtype=torch.float16)

    batch_input_ids = [tokenizer_image_token(prompt, tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pt").unsqueeze(0).to("cuda:"+str(rank)) for prompt in prompts]
    max_len = max([len(seq) for seq in batch_input_ids])
    padded_input_ids = [pad_sequence_to_max_length(seq.squeeze(), max_len) for seq in batch_input_ids]
    batch_input_ids = torch.stack(padded_input_ids)

    with torch.inference_mode():
        output_ids = model.generate(
            batch_input_ids,
            images=images_tensor,
            image_sizes=image_sizes,
            do_sample=True,
            temperature=0.2,
            top_p=None,
            num_beams=1,
            max_new_tokens=5,
            use_cache=True,
        ).to("cuda:"+str(rank))

    outputs = tokenizer.batch_decode(output_ids, skip_special_tokens=True)
    return outputs
```

**Comment by Jason-Chi-xx** [comment]
> > Hi, I have encountered a problem when running the inference code of llava-next. That is the length of input_ids and images are 9, but the model.generate function would only return the output_ids with length 1: output_ids = self.model.generate( input_ids, images=image_tensor, image_sizes=self.image_sizes, use_cache=True, stopping_criteria=stopping_criteria, do_sample=False, temperature=0, max_new_tokens=256, ) Does someone know the solution? thanks
> 
> @Jason-Chi-xx Please make sure the input_ids are concatenated. Here are the codes for batched inference:
> 
> ```
> def load_model(rank):
>     device = "cuda:" + str(rank)
>     model_name = get_model_name_from_path(model_path)
>     tokenizer, model, image_processor, context_len = load_pretrained_model(
>     model_path, None, model_name, False, False, device
>     )
>     return tokenizer, model, image_processor, context_len
> 
> def pad_sequence_to_max_length(sequence, max_length, padding_value=0):
>     """Pad a sequence to the desired max length."""
>     if len(sequence) >= max_length:
>         return sequence
>     return torch.cat([torch.full((max_length - len(sequence),), padding_value, dtype=sequence.dtype), sequence])
> 
> """rank is your device id, qs is the textual prompt, frames are batched images. Tokenizer, model, and image_processor can be obtained when you run load_model."""
> def batched_inference(rank, qs, frames, tokenizer, model, image_processor):
>     disable_torch_init()
>     model_name = get_model_name_from_path(model_path)
>     image_token_se = DEFAULT_IM_START_TOKEN + DEFAULT_IMAGE_TOKEN + DEFAULT_IM_END_TOKEN
>     if IMAGE_PLACEHOLDER in qs:
>         if model.config.mm_use_im_start_end:
>             qs = re.sub(IMAGE_PLACEHOLDER, image_token_se, qs)
>         else:
>             qs = re.sub(IMAGE_PLACEHOLDER, DEFAULT_IMAGE_TOKEN, qs)
>     else:
>         if model.config.mm_use_im_start_end:
>             qs = image_token_se + "\n" + qs
>         else:
>             qs = DEFAULT_IMAGE_TOKEN + "\n" + qs
>     # print(qs)
>     if "llama-2" in model_name.lower():
>         conv_mode = "llava_llama_2"
>     elif "mistral" in model_name.lower():
>         conv_mode = "mistral_instruct"
>     elif "v1.6-34b" in model_name.lower():
>         conv_mode = "chatml_direct"
>     elif "v1" in model_name.lower():
>         conv_mode = "llava_v1"
>     elif "mpt" in model_name.lower():
>         conv_mode = "mpt"
>     else:
>         conv_mode = "llava_v0"
> 
>     conv = conv_templates[conv_mode].copy()
>     conv.append_message(conv.roles[0], qs)
>     conv.append_message(conv.roles[1], None)
>     prompts = []
>     for i in range(len(frames)):
>         prompt = conv.get_prompt()
>         prompts.append(prompt)
>     pil_images = []
>     for frame in frames:
>         rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
>         pil_image = Image.fromarray(rgb_frame)
>         pil_images.append(pil_image)
>     image_sizes = [x.size for x in pil_images]
>     
>     images_tensor = process_images(
>         pil_images,
>         image_processor,
>         model.config
>     ).to("cuda:"+str(rank), dtype=torch.float16)
> 
>     batch_input_ids = [tokenizer_image_token(prompt, tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pt").unsqueeze(0).to("cuda:"+str(rank)) for prompt in prompts]
>     max_len = max([len(seq) for seq in batch_input_ids])
>     padded_input_ids = [pad_sequence_to_max_length(seq.squeeze(), max_len) for seq in batch_input_ids]
>     batch_input_ids = torch.stack(padded_input_ids)
> 
>     with torch.inference_mode():
>         output_ids = model.generate(
>             batch_input_ids,
>             images=images_tensor,
>             image_sizes=image_sizes,
>             do_sample=True,
>             temperature=0.2,
>             top_p=None,
>             num_beams=1,
>             max_new_tokens=5,
>             use_cache=True,
>         ).to("cuda:"+str(rank))
> 
>     outputs = tokenizer.batch_decode(output_ids, skip_special_tokens=True)
>     return outputs
> ```

Thank you very much!

**Comment by Jason-Chi-xx** [comment]
> @Jason-Chi-xx The model will generate tokens up to `max_new_tokens` and `1` is a feasible length in case the model just generates "eos" as the very first token. Please make sure your prompt is formatted correctly to get a quality generation. I recommend to use `apply_chat_template` for formatting your prompt

Thanks for your help!
